### ISSUE TITLE
Infection date already set

### ISSUE THREAD

**Issue by andyb87** [matsim-org/matsim-episim#12]
Dear episim Developer Team,

I just came across this new simulation tool and started "playing" with it.
I have a ready build simulation and tried to run an episim simulation with it, howeverI run across the following problem: 

```
2020-04-03T13:40:17,060  INFO EventsManagerImpl:135  event # 1
2020-04-03T13:40:17,069  INFO EventsManagerImpl:135  event # 4
2020-04-03T13:40:17,069  WARN InfectionEventHandler:276  person 642972 has initial infection
2020-04-03T13:40:17,069  WARN InfectionEventHandler:276  person 893453 has initial infection
2020-04-03T13:40:17,071  WARN InfectionEventHandler:276  person 824877 has initial infection
2020-04-03T13:40:17,073  WARN InfectionEventHandler:276  person 223589 has initial infection
2020-04-03T13:40:17,074  WARN InfectionEventHandler:276  person 413878 has initial infection
2020-04-03T13:40:17,074  WARN InfectionEventHandler:276  person 598562 has initial infection
2020-04-03T13:40:17,075  WARN InfectionEventHandler:276  person 85789 has initial infection
Exception in thread "main" java.lang.IllegalStateException: Infection date already set
	at org.matsim.episim.EpisimPerson.setInfectionDate(EpisimPerson.java:84)
	at org.matsim.episim.InfectionEventHandler.handleInitialInfections(InfectionEventHandler.java:275)
	at org.matsim.episim.InfectionEventHandler.handleEvent(InfectionEventHandler.java:140)
	at org.matsim.core.events.EventsManagerImpl.callHandlerFast(EventsManagerImpl.java:284)
	at org.matsim.core.events.EventsManagerImpl.processEvent(EventsManagerImpl.java:139)
	at org.matsim.episim.ReplayHandler.replayEvents(ReplayHandler.java:71)
	at org.matsim.run.RunEpisim.runSimulation(RunEpisim.java:187)
	at org.matsim.run.RunEpisim.main(RunEpisim.java:77)
2020-04-03T13:40:17,074  INFO EventsManagerImpl:135  event # 16

Process finished with exit code 1
```

I traced back the issue to the following line:

https://github.com/matsim-org/matsim-episim/blob/21adea6b5bd36bbe4109f69c04fd2f4a72ea870b/src/main/java/org/matsim/episim/EpisimPerson.java#L79-L84

... and I have figured out two walkarounds:

1.  Either by commenting out the conditional statement above or
2. by reducing the number of initially infected persons to below the number get infected in the consol output, eg. in my example above to to 7

Please could you tell me briefly the purpose of the conditional statement and why this error occurs in my case?

Many thanks in advance!
Andy

**Comment by tschlenther** [comment]
Hello,

this is related to the assignment of initial infections which recently has undergone a change. Are you running the up-to-date version?

Best

Tilmann
