### ISSUE TITLE
Supported event types

### ISSUE THREAD

**Issue by gac55** [matsim-org/matsim-episim#31]
Thanks for the great work.

We have been attempting to apply this on some existing models.

Whilst debugging some issues that manifest themselves in the infection handlers it has become clear that the `events` file we are inputting contains events that are not needed nor supported.

Events such as `left link` and `entered link` for a `vehicle` and `TransitDriverStarts` for a PT route are outputted from our simulation and it makes sense that these are not relevant for this and should be removed.

Is there a specific list to identify which event types are required and/or supported? I am in the process of reverse-engineering this and apologies if I have missed existing documentation/explanations.

I'm aware of the `downSample` function but this appears to sample from the events and not perform filtering by type.

**Comment by rakow** [comment]
Hi,

the `downSample` function is indeed what you are looking for. It does not only sample but also filters the relevant events. You may have a look at the [FilterHandler](https://github.com/matsim-org/matsim-episim/blob/develop/src/main/java/org/matsim/scenarioCreation/FilterHandler.java).

At the moment, the required events are `ActivityEndEvent`, `ActivityStartEvent`, `PersonEntersVehicleEvent`, `PersonLeavesVehicleEvent`.
Any additional events can also be present but episim should ignore these.

**Comment by captainnemo2005** [comment]
Hi just one quick question, in the downsample they required a facilities path file, and you have facilities for home and education, i just wonder what facilities should be used in here?

**Comment by captainnemo2005** [comment]
Hi, really love you work and current i am feeding the Runepisim with my event file for melbourne. Can you provide the stand config.xml file so that I can map it with me parameters.

Thank so much

**Comment by rakow** [comment]
Could you try `episimConfig.setFacilitiesHandling( EpisimConfigGroup.FacilitiesHandling.bln )` in your config (if not done already).

 I think there are no facility ids present in the events. I will also add a warning for this.
With the config above it should work without facility ids though.

**Comment by captainnemo2005** [comment]
hi, thanks for your reply but this line was set in the configuregroup as default. 
I try to run the file RunEpisim with your default by you but receive this messgase:
 Unable to provision, see the following errors:

1) Error injecting constructor, org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: ../public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/berlin-v5.4-1pct.output_events_for_episim.xml.gz
  at org.matsim.episim.ReplayHandler.<init>(ReplayHandler.java:52)
  at org.matsim.episim.EpisimModule.configure(EpisimModule.java:57) (via modules: com.google.inject.util.Modules$OverrideModule -> org.matsim.episim.EpisimModule)
  while locating org.matsim.episim.ReplayHandler

1 error
	at com.google.inject.internal.InternalProvisionException.toProvisionException(InternalProvisionException.java:226)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1053)
	at org.matsim.episim.EpisimRunner.run(EpisimRunner.java:62)
	at org.matsim.run.RunEpisim.call(RunEpisim.java:170)
	at org.matsim.run.RunEpisim.call(RunEpisim.java:1)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
	at picocli.CommandLine.access$900(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
	at picocli.CommandLine.execute(CommandLine.java:1904)
	at org.matsim.run.RunEpisim.main(RunEpisim.java:101)
Caused by: org.matsim.core.utils.io.UncheckedIOException: java.io.FileNotFoundException: ../public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/berlin-v5.4-1pct.output_events_for_episim.xml.gz
	at org.matsim.core.utils.io.IOUtils.resolveFileOrResource(IOUtils.java:212)
	at org.matsim.core.utils.io.IOUtils.getBufferedReader(IOUtils.java:486)
	at org.matsim.core.utils.io.MatsimXmlParser.readFile(MatsimXmlParser.java:149)
	at org.matsim.core.events.MatsimEventsReader.readFile(MatsimEventsReader.java:79)
	at org.matsim.core.events.EventsUtils.readEvents(EventsUtils.java:65)
	at org.matsim.episim.ReplayHandler.<init>(ReplayHandler.java:57)
	at org.matsim.episim.ReplayHandler$$FastClassByGuice$$7d5a651b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1050)
	... 11 more
Caused by: java.io.FileNotFoundException: ../public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/berlin-v5.4-1pct.output_events_for_episim.xml.gz
	at org.matsim.core.utils.io.IOUtils.resolveFileOrResource(IOUtils.java:210)
	... 25 more
They link me to the EpisimConfigTest and EpisimConfigGroup.

**Comment by rakow** [comment]
Unfortunately the example contains a relative file path.

Could you replace the input event file path with the url? You can find the file here:
https://svn.vsp.tu-berlin.de/repos/public-svn/matsim/scenarios/countries/de/berlin/berlin-v5.4-1pct/output-berlin-v5.4-1pct/berlin-v5.4-1pct.output_events_for_episim.xml.gz

Alternatively you could also put the file at the location mentioned in the error message.

I have also adapted the config on the `develop` branch, so it should work out of the box now.

**Comment by captainnemo2005** [comment]
Hi, i just remove and install back the project but they didn't generate the episim.jar file anymore.

**Comment by captainnemo2005** [comment]
I think there is something wrong with the installation. since i just redownload and re-installed the package but they showed couple of bug about package like import org.matsim.episim can't be resolve in couple files.

I also attempted to replace the directory and re-run the *jar file but it seem that the system doesn't realize by changes.

**Comment by rakow** [comment]
Please try `mvn clean package` to make sure every outdated file is removed.

**Comment by captainnemo2005** [comment]
the installation is success but when i set the new path for String episimEvents_1pct in OpenBerlineScenario and run it with the Jar snapshot in terminal they keep showing the old path with /public-svn/.....
I tried both on windows and mac and receive them same result.

**Comment by rakow** [comment]
Please pull the newest version from github again. It should include the most recent changes now.
But it sounds like a problem with the build if your changes didn't have any effect. Please double check if you edited and executed the correct files.

**Comment by captainnemo2005** [comment]
Hi, thanks for your responds.
Do the jar file you provide has any source of session or cache since regardless to the change it always remember the set up from you.

**Comment by captainnemo2005** [comment]
just a quick fix in the .EpisimConfigGroup.selectInfectionParam make the stuff run but i dont know how large it impact the solution

**Comment by rakow** [comment]
There needs to be infection parameters for each activity type in the scenario.  As example, you may look at the scenario here: https://github.com/matsim-org/matsim-episim/blob/d45627378a7fb9f00f046876381ecd576dc93db4/src/main/java/org/matsim/run/modules/OpenBerlinScenario.java#L46

I don't know what types you have in your scenario, but it looks like the conventions might be different from the scenarios we are using.
In this case adapting `selectInfectionParams ` might be a reasonable way to change how activities are mapped to infection parameters.

**Comment by gac55** [comment]
Thanks @rakow for your help on the query.

**Comment by captainnemo2005** [comment]
Hi Rakow,

just one quick update for people who suffer from mapping event type that are ignore.
